admin_homepage:
    path:     /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: admin_dashboard
        permanent: true

admin_dashboard:
    path:     /dashboard
    defaults: { _controller: AdminBundle:Dashboard:index }

admin_login:
    path:     /login
    defaults: { _controller: AdminBundle:Login:index }